apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    router.openshift.io/cookie_name: lfrstickysessioncookie
  labels:
    helm/app-name: {{ .Values.appName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
{{- if .Values.service.name }}
           name: {{ .Values.service.name }}
{{- else }}
           name: {{ .Release.Name }}
{{- end }}
           port:
             number: {{ .Values.service.externalPort }}