env: dev
replicas: 1
resources:
  requests:
    memory: "6Gi"
    cpu: "4"
  limits:
    memory: "6Gi"
    cpu: "4"
       
extraEnv:
  - name: LIFERAY_JVM_OPTS
    value: -XX:NewRatio=2 -Xms4G -Xmx4G -XX:+UseG1GC -XX:+UseCompressedOops -XX:+DisableExplicitGC
  - name: JAVA_VERSION
    value: zulu8
  - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE
    value: "true"

confElasticsearchConnector:
  enabled: true
  mountAsVolume: true
  mountPath: "/opt/liferay/osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config"
  subPath: "com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config"
  name: conf-elasticsearch-connector 

autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuThreshold: 80
  memoryThreshold: 90
  
service:
  host: dev.liferay.openshift.com